fix: memory leak from temp vsimem datasets in GDAL tile factory
aws-solutions-library-samples/osml-imagery-toolkit pull request #20
Opened 2023-10-02 19:39 UTC by edparris

This change fixes a memory leak caused by not deleting the temporary [GDAL vsimem virtual file system](https://gdal.org/user/virtual_file_systems.html#vsimem-in-memory-files) created for each tile by the GDALTileFactory. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-10-02 22:30 UTC, drduhe approved these changes
Nice job - LGTM

2023-10-02 22:34 UTC, drduhe requested changes
This was an accident

2023-10-02 22:58 UTC, RanbirAulakh approved these changes

2023-10-02 23:12 UTC, drduhe approved these changes

2023-10-03 03:38 UTC, drduhe approved these changes
TY for the additional hotfix

2023-10-03 03:40 UTC, merged